version: '2'

services:

  etcd:
    image: quay.io/coreos/etcd:v3.0.10
    command: /usr/local/bin/etcd -data-dir=/data -listen-peer-urls="http://172.10.1.2:7001,http://172.10.1.2:2380" -listen-client-urls="http://172.10.1.2:4001,http://172.10.1.2:2379" -advertise-client-urls="http://172.10.1.2:4001"
    expose:
      - 2380
      - 2379
      - 4001
      - 7001
    networks:
      net:
        ipv4_address: 172.10.1.2

  whoami1:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - etcd
    networks:
      net:
        ipv4_address: 172.10.1.3

  whoami2:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - whoami1
    networks:
      net:
        ipv4_address: 172.10.1.4

  whoami3:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - whoami2
    networks:
      net:
        ipv4_address: 172.10.1.5

  whoami4:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - whoami3
    networks:
      net:
        ipv4_address: 172.10.1.6

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.1.0/28