# ...
[entrypoints]
  [entrypoints.web]
    address = ":80"

    [entrypoints.web.proxyProtocol]
      insecure = true
      trustedIPs = ["10.10.10.1", "10.10.10.2"]

    [entrypoints.web.forwardedHeaders]
      trustedIPs = ["10.10.10.1", "10.10.10.2"]
      insecure = false

  [entrypoints.web-secure]
    # ...